Controllers/DanhmucController.cs
using FashionStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FashionStore.Controllers
{
    public class DanhmucController : Controller
    {
        FashionStoreEntities db = new FashionStoreEntities();

        public ActionResult danhmucpartial()
        {
            var danhmuc = db.LoaiHangs.ToList();
            return PartialView(danhmuc);

        }
    }
}

Controllers/DonhangController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FashionStore.Models;

namespace FashionStore.Controllers
{
    public class DonhangController : Controller
    {
        private FashionStoreEntities db = new FashionStoreEntities();

        // GET: Donhangs
        // Hiển thị danh sách đơn hàng
        public ActionResult Index()
        {
            //Kiểm tra đang đăng nhập
            if (Session["use"] == null || Session["use"].ToString() == "")
            {
                return RedirectToAction("Dangnhap", "User");
            }
            TaiKhoan kh = (TaiKhoan)Session["use"];
            int maND = kh.MaNguoiDung;
            var donhangs = db.DonHangs.Include(d => d.TaiKhoan).Where(d => d.MaNguoiDung == maND);
            return View(donhangs.ToList());
        }

        // GET: Donhangs/Details/5
        //Hiển thị chi tiết đơn hàng
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            var chitiet = db.ChiTietDonHangs.Include(d => d.SanPham).Where(d => d.MaDon == id).ToList();
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/SanphamController.cs
using FashionStore.Models;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using System.Data.Entity;
using System.IO;

namespace FashionStore.Controllers
{
    public class SanphamController : Controller
    {
        private FashionStoreEntities db = new FashionStoreEntities();

        // GET: Sanpham
        public ActionResult Index()
        {
            var sanPhams = db.SanPhams
                             .Include(s => s.LoaiHang)
                             .Include(s => s.NhaCungCap)
                             .ToList();
            return View(sanPhams);
        }

        public ActionResult GetProductImage(string imageName)
        {
            if (string.IsNullOrEmpty(imageName))
                return File(Server.MapPath("~/Images/default-product.jpg"), "image/jpeg");

            var path = Server.MapPath("~/Images/" + imageName);
            if (!System.IO.File.Exists(path))
                return File(Server.MapPath("~/Images/default-product.jpg"), "image/jpeg");

            // Đọc file và trả về
            return File(path, "image/jpeg", imageName);
        }

        public ActionResult SanPhamBanChay()
        {
            var sanPhamBanChay = db.SanPhams
                .Include(s => s.LoaiHang)
                .Include(s => s.NhaCungCap)
                .OrderByDescending(p => p.SoLuong) // Sắp xếp theo số lượng bán giảm dần
                .Take(8) // Lấy 10 sản phẩm bán chạy nhất
                .ToList();

            return View(sanPhamBanChay);
        }


        public ActionResult AoBestSeller()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 1).Take(4).ToList();
            return PartialView("suapartial", ip);
        }

        public ActionResult QuanBestSeller()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 2).Take(4).ToList();
            return PartialView("QuanBestSeller", ip);
        }

        public ActionResult VayDamBestSeller()
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == 3).Take(4).ToList();
            return PartialView("VayDamBestSeller", ip);
        }

        public ActionResult xemchitiet(int Masp = 0)
        {
            var chitiet = db.SanPhams.SingleOrDefault(n => n.MaSP == Masp);
            if (chitiet == null)
            {
                return HttpNotFound("Sản phẩm không tồn tại");
            }
            return View(chitiet);
        }

        public ActionResult xemchitietdanhmuc(int MaLoai)
        {
            var ip = db.SanPhams.Where(n => n.MaLoai == MaLoai).ToList();
            if (ip == null || !ip.Any())
            {
                return HttpNotFound("Không tìm thấy sản phẩm cho loại này");
            }
            return PartialView(ip);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Controllers/UserController.cs
using FashionStore.Models;
using Microsoft.Ajax.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FashionStore.Controllers
{
    public class UserController : Controller
    {
        FashionStoreEntities db = new FashionStoreEntities();

        // ĐĂNG KÝ
        public ActionResult Dangky()
        {
            return View();
        }

        // ĐĂNG KÝ PHƯƠNG THỨC POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Dangky(TaiKhoan taiKhoan)
        {
            try
            {
                Session["userReg"] = taiKhoan;


                // Nếu dữ liệu đúng thì trả về trang đăng nhập
                if (ModelState.IsValid)
                {
                    var check = db.TaiKhoans.FirstOrDefault(s => s.Email == taiKhoan.Email);
                    if (check == null)
                    {
                        taiKhoan.IDQuyen = 2;

                        db.TaiKhoans.Add(taiKhoan);
                        db.SaveChanges();

                        ViewBag.RegOk = "Đăng kí thành công. Đăng nhập ngay";
                        ViewBag.isReg = true;
                        return View("Dangky");
                    }
                    else
                    {
                        ViewBag.RegOk = "Email đã tồn tại! Vui lòng chọn 1 email khác";
                        return View("Dangky");
                    }

                }
                {
                    return View("Dangky");
                }
                    

            }
            catch
            {
                return View();
            }
        }

        [AllowAnonymous]
        public ActionResult Dangnhap()
        {
            return View();

        }


        [HttpPost]
        public ActionResult Dangnhap(FormCollection userlog)
        {
            string userMail = userlog["userMail"].ToString();
            string password = userlog["password"].ToString();
            var islogin = db.TaiKhoans.FirstOrDefault(x => x.Email.Equals(userMail) && x.MatKhau.Equals(password));

            if (islogin != null)
            {
                if (userMail == "admin@gmail.com")
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Admin/Home");
                }
                else
                {
                    Session["use"] = islogin;
                    return RedirectToAction("Index", "Home");
                }
            }
            else
            {
                ViewBag.Fail = "Tài khoản hoặc mật khẩu không chính xác.";
                return View("Dangnhap");
            }

        }
        public ActionResult DangXuat()
        {
            Session["use"] = null;
            return RedirectToAction("Index", "Home");

        }

            new public ActionResult Profile(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            return View(taiKhoan);
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TaiKhoan taiKhoan = db.TaiKhoans.Find(id);
            if (taiKhoan == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }

        // POST: Admin/Nguoidungs/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaNguoiDung,HoTen,Email,Dienthoai,Matkhau,IDQuyen,Diachi")] TaiKhoan taiKhoan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(taiKhoan).State = EntityState.Modified;
                db.SaveChanges();
                //@ViewBag.show = "Chỉnh sửa hồ sơ thành công";
                //return View(nguoidung);
                return RedirectToAction("Profile", new { id = taiKhoan.MaNguoiDung });

            }
            ViewBag.IDQuyen = new SelectList(db.PhanQuyens, "IDQuyen", "TenQuyen", taiKhoan.IDQuyen);
            return View(taiKhoan);
        }
        public static byte[] encryptData(string data)
        {
            System.Security.Cryptography.MD5CryptoServiceProvider md5Hasher = new System.Security.Cryptography.MD5CryptoServiceProvider();
            byte[] hashedBytes;
            System.Text.UTF8Encoding encoder = new System.Text.UTF8Encoding();
            hashedBytes = md5Hasher.ComputeHash(encoder.GetBytes(data));
            return hashedBytes;
        }
        public static string md5(string data)
        {
            return BitConverter.ToString(encryptData(data)).Replace("-", "").ToLower();
        }
    }
}

Views/Shared/_LayoutClient.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="/Home/css/styles.css" rel="stylesheet" />
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="~/css/styles.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    @{ var u = Session["use"] as FashionStore.Models.TaiKhoan; }
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("SHOPDT", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"> </span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("Giới thiệu", "About", "Home", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </li>
                    <li class="nav-item mx-0 mx-lg-1 dropdown">@Html.ActionLink("Sản phẩm", "index", "Sanpham", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </li>
       
                    <li class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("Liên hệ", "Contact", "Home", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </li>              
                </ul>

                <ul class="navbar-nav ms-auto">
                    <li class="nav-item mx-0 mx-lg-1">  @Html.Action("GioHangPartial", "Giohang", new { @class = "giohang" }) </li>
                </ul>

                <ul class="navbar-nav ms-auto ">
                    @{ if (u != null)
                        {
                            <li class="nav-item mx-0 mx-lg-1">
                                <a style="color:white" href="@Url.Action("Profile", "User", new { id = u.MaNguoiDung  })"> Xin chào: @u.Email</a>
                                <br />
                                <a style="color:red" href="/User/DangXuat"> ĐĂNG XUẤT</a>
                            </li>

                        }
                        else
                        {
                            <td class="nav-item mx-0 mx-lg-1"> @Html.ActionLink("Đăng nhập", "Dangnhap", "User", new { area = "" }, new { @class = "nav-link py-3 px-0 px-lg-3 rounded" }) </td>

                        } }
                </ul>
            </div>
      </div>
            </nav>
            <div class="container body-content">
                @RenderBody()
                <hr />
            </div>

            @Scripts.Render("~/bundles/jquery")
            @Scripts.Render("~/bundles/bootstrap")
            @RenderSection("scripts", required: false)
        </body>

        <!-- Footer-->
        <footer class="text-bg-success" style="padding-left:50px">
            <div class="row">
                <div class="col-md-3 col-sm-6">
                    <h2>Chính sách</h2>
                    <span>Chính sách mua hàng</span>
                    <br />
                    <span>Chính sách khách hàng</span>
                    <br />
                    <span>Chính sách giao hàng</span>
                </div>
                <div class="col-md-3 col-sm-6">
                    <h2>Liên kết</h2>
                    <span>Tin tức</span>
                    <br />
                    <span>Tuyển dụng</span>
                    <br />
                    <span>Hướng dẫn mua hàng</span>
                    <br />
                    <span>Hỏi đáp</span>


                </div>
                <div class="col-md-3 col-sm-6">
                    <h2>Thông tin</h2>
                    <span>Về chúng tôi</span>
                    <br />
                    <span>Liên hệ</span>
                    <br />
                    <span>Góp ý</span>
                    <br />
                    <span>Tra cứu</span>
                </div>
                <div class="col-md-3 col-sm-6">
                    <h2>Theo dõi</h2>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                    <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>

                </div>
            </div>
            <hr />
            <!-- Copyright Section-->
            <div class="copyright py-4 text-center text-white">
                <div class="container"><small>Copyright &copy; Thời trang nam nữ - Molla</small></div>
            </div>
        </footer>

        <script src="~/Content/ckeditor/ckfinder/ckfinder.js"></script>

        <script src="~/Content/ckeditor/ckeditor.js"></script>

        <script src="~/Content/ckeditor/adapters/jquery.js"></script>


        <script>
        </script>

        @RenderSection("DoanJS", false)
    </html>

Views/Shared/_LayoutClient2.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="Trendy Mall Fashion Store - Thời trang cao cấp" />
    <meta name="author" content="Your Name" />
    <title>@ViewBag.Title Mall Fashion Store</title>

    <!-- Favicon -->
    <link rel="icon" href="~/Images/logo-icon.png" />

    <!-- CSS -->
    <link href="https://fonts.googleapis.com/css2?family=Crimson+Text:wght@400;600;700&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet" />
    @Styles.Render("~/Content/css")

    <style>
        :root {
            --primary-color: #2C3E50;
            --secondary-color: #CC9966;
            --white: #ffffff;
            --dark: #333333;
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
            font-family: 'Crimson Text', serif;
        }

        body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }

        .wrapper {
            flex: 1 0 auto;
        }

        /* Navbar Styles */
        .navbar {
            background-color: var(--white) !important;
            box-shadow: 0 2px 5px rgba(0,0,0,0.06);
            padding: 15px 0;
        }

        .navbar-brand img {
            height: 50px;
            width: auto;
        }

        .nav-link {
            color: var(--primary-color) !important;
            font-size: 18px;
            font-weight: 600;
            padding: 8px 16px !important;
            transition: all 0.3s ease;
        }

        .nav-link:hover {
            color: var(--secondary-color) !important;
        }

        /* Dropdown Styles */
        .dropdown-menu {
            border: none;
            box-shadow: 0 4px 12px rgba(0,0,0,0.1);
            animation: fadeIn 0.3s ease;
        }

        .dropdown-item {
            padding: 8px 20px;
            transition: all 0.3s ease;
            color: var(--dark);
        }

        .dropdown-item:hover {
            background-color: #f8f9fa;
            transform: translateX(5px);
            color: var(--secondary-color);
        }

        /* Button Styles */
        .btn-cart, .auth-button {
            text-decoration: none;
            padding: 8px 16px;
            border-radius: 4px;
            transition: all 0.3s ease;
            font-size: 15px;
            font-weight: 500;
        }
        .btn-cart a{
            text-decoration: none;
        }

        .btn-cart {
            text-decoration: none;
            border: 1px solid var(--primary-color);
            color: var(--primary-color);
            margin-right: 15px;
        }

        .btn-cart:hover {
            background-color: var(--primary-color);
            color: var(--white);
        }

        .auth-buttons {
            display: flex;
            gap: 10px;
        }

        .btn-signup {
            background-color: var(--primary-color);
            color: var(--white) !important;
            border: 1px solid var(--primary-color);
        }

        .btn-login {
            border: 1px solid var(--primary-color);
            color: var(--primary-color) !important;
        }

        /* User Profile */
        .user-profile {
            display: flex;
            align-items: center;
            gap: 15px;
        }

        .user-greeting {
            color: var(--primary-color);
            font-size: 15px;
        }

        .btn-logout {
            background-color: #e74c3c;
            color: var(--white) !important;
            padding: 8px 16px;
            border-radius: 4px;
            transition: all 0.3s ease;
        }

        /* Footer Styles */
        footer {
            background-color: var(--primary-color);
            color: var(--white);
            padding: 40px 0 0;
        }

        footer h5 {
            font-weight: 600;
            margin-bottom: 20px;
        }

        footer a {
            color: var(--white);
            text-decoration: none;
            transition: all 0.3s ease;
        }

        footer a:hover {
            color: var(--secondary-color) !important;
        }

        .footer-bottom {
            background-color: rgba(0, 0, 0, 0.2);
            padding: 15px 0;
            margin-top: 30px;
        }

        /* Animations */
        @@keyframes fadeIn {
            from {
                opacity: 0;
                transform: translateY(-10px);
            }
            to {
                opacity: 1;
                transform: translateY(0);
            }
        }

        /* Responsive */
        @@media (max-width: 768px) {
            .auth-buttons {
                margin-top: 10px;
            }

            .navbar-nav {
                margin-top: 15px;
            }
        }
    </style>
</head>

<body>
    @{ var u = Session["use"] as FashionStore.Models.TaiKhoan; }

    <div class="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-light">
            <div class="container">
                <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                    <img src="~/Images/logo.png" alt="Trendy Mall" />
                </a>

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarContent">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            @Html.ActionLink("Trang chủ", "Index", "Home", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item">
                            @Html.ActionLink("Giới thiệu", "About", "Home", null, new { @class = "nav-link" })
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" data-bs-toggle="dropdown">
                                Sản phẩm
                            </a>
                            <ul class="dropdown-menu">
                                <li>
                                    @Html.ActionLink("Tất cả sản phẩm", "Index", "Sanpham", null,
                                new { @class = "dropdown-item" })
                            </li>
                            <li><hr class="dropdown-divider"></li>
                            <li>@Html.Action("danhmucpartial", "Danhmuc")</li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Liên hệ", "Contact", "Home", null, new { @class = "nav-link" })
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Đơn hàng", "Index", "Donhang", null, new { @class = "nav-link" })
                    </li>
                </ul>

                <div class="d-flex align-items-center">
                    <button class="btn-cart">
                        @Html.Action("GioHangPartial", "Giohang")
                    </button>

                    @if (u != null)
                    {
                        <div class="user-profile">
                            <span class="user-greeting">Xin chào: @u.Email</span>
                            <a href="/User/DangXuat" class="btn-logout">Đăng xuất</a>
                        </div>
                    }
                    else
                    {
                        <div class="auth-buttons">
                            <a href="@Url.Action("Dangky", "User")" class="auth-button btn-signup">Đăng ký</a>
                            <a href="@Url.Action("Dangnhap", "User")" class="auth-button btn-login">Đăng nhập</a>
                        </div>
                    }
                </div>
            </div>
        </div>
    </nav>

    <!-- Main Content -->
    <main class="flex-grow-1">
        @RenderBody()
    </main>
</div>

<!-- Footer -->
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-4 mb-4">
                <h5>Liên hệ</h5>
                <p><i class="fas fa-home me-3"></i> 1168/9 Lê Văn Lương, Nhà Bè, TP.HCM</p>
                <p><i class="fas fa-envelope me-3"></i> nguyensonttag@gmail.com</p>
                <p><i class="fas fa-phone me-3"></i> +84384809098</p>
            </div>

            <div class="col-lg-4 mb-4">
                <h5>Liên kết nhanh</h5>
                <ul class="list-unstyled">
                    <li><a href="@Url.Action("Index", "Home")">Trang chủ</a></li>
                    <li><a href="@Url.Action("About", "Home")">Giới thiệu</a></li>
                    <li><a href="@Url.Action("Index", "Sanpham")">Sản phẩm</a></li>
                    <li><a href="@Url.Action("Contact", "Home")">Liên hệ</a></li>
                </ul>
            </div>

            <div class="col-lg-4">
                <h5>Theo dõi chúng tôi</h5>
                <div class="social-links mb-4">
                    <a href="#"><i class="fab fa-facebook-f"></i></a>
                    <a href="#"><i class="fab fa-twitter"></i></a>
                    <a href="#"><i class="fab fa-instagram"></i></a>
                </div>

                <h5>Đăng ký nhận tin</h5>
                <div class="input-group">
                    <input type="email" class="form-control" placeholder="Email của bạn">
                    <button class="btn btn-outline-light">Đăng ký</button>
                </div>
            </div>
        </div>
    </div>

    <div class="footer-bottom text-center">
        <p class="mb-0">© 2024 Trendy Mall Fashion Store. All rights reserved.</p>
    </div>
</footer>

<!-- Scripts -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"></script>

<script>
    $(document).ready(function () {
        // Active nav link
        const currentPath = window.location.pathname;
        $('.nav-link').each(function () {
            if ($(this).attr('href') === currentPath) {
                $(this).addClass('active');
            }
        });

        // Dropdown hover
        $('.dropdown').hover(
            function () { $(this).find('.dropdown-menu').stop().fadeIn(200); },
            function () { $(this).find('.dropdown-menu').stop().fadeOut(200); }
        );

        // Responsive menu
        $('.navbar-toggler').click(function () {
            $('.navbar-collapse').toggleClass('show');
        });

        // Close menu when clicking outside
        $(document).click(function (e) {
            if (!$(e.target).closest('.navbar').length) {
                $('.navbar-collapse').removeClass('show');
            }
        });
    });
</script>

@RenderSection("scripts", required: false)
</body>
</html>