Areas/Admin/Controllers/DonHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FashionStore.Models;

namespace FashionStore.Areas.Admin.Controllers
{
    public class DonHangsController : Controller
    {
        private FashionStoreEntities db = new FashionStoreEntities();

        // GET: DonHangs
        public ActionResult Index()
        {
            var donHangs = db.DonHangs.Include(d => d.TaiKhoan);
            var u = Session["use"] as FashionStore.Models.TaiKhoan;
            if (u.PhanQuyen.TenQuyen == "Adminstrator")
            {
                return View(donHangs.OrderByDescending(s => s.MaDon).ToList());
            }
            return RedirectPermanent("~/Home/Index");

        }

        // GET: DonHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        public ActionResult CTDetails(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donhang = db.DonHangs.Find(id);
            var chitiet = db.ChiTietDonHangs.Include(d => d.SanPham).Where(d => d.MaDon == id).ToList();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return View(chitiet);
        }

        // GET: DonHangs/Create
        public ActionResult Create()
        {
            ViewBag.MaNguoiDung = new SelectList(db.TaiKhoans, "MaNguoiDung", "HoTen");
            return View();
        }

        // POST: DonHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Madon,NgayDat,TinhTrang,ThanhToan,DiaChiNhanHang,MaNguoiDung,TongTien")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.DonHangs.Add(donHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MaNguoiDung = new SelectList(db.TaiKhoans, "MaNguoiDung", "HoTen", donHang.MaNguoiDung);
            return View(donHang);
        }

        // GET: DonHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaNguoiDung = new SelectList(db.TaiKhoans, "MaNguoiDung", "HoTen", donHang.MaNguoiDung);
            return View(donHang);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Madon,NgayDat,TinhTrang,ThanhToan,DiaChiNhanHang,MaNguoiDung,TongTien")] DonHang donHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(donHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MaNguoiDung = new SelectList(db.TaiKhoans, "MaNguoiDung", "HoTen", donHang.MaNguoiDung);
            return View(donHang);
        }



        // GET: DonHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donHang = db.DonHangs.Find(id);
            if (donHang == null)
            {
                return HttpNotFound();
            }
            return View(donHang);
        }

        // POST: DonHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DonHang donHang = db.DonHangs.Find(id);
            db.DonHangs.Remove(donHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Xacnhan(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DonHang donhang = db.DonHangs.Find(id);
            donhang.TinhTrang = 1;
            db.SaveChanges();
            if (donhang == null)
            {
                return HttpNotFound();
            }
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Controllers/LoaiHangsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FashionStore.Models;

namespace FashionStore.Areas.Admin.Controllers
{
    public class LoaiHangsController : Controller
    {
        private FashionStoreEntities db = new FashionStoreEntities();

        // GET: LoaiHangs
        public ActionResult Index()
        {
            var u = Session["use"] as FashionStore.Models.TaiKhoan;
            if (u.PhanQuyen.TenQuyen == "Adminstrator")
            {
                return View(db.LoaiHangs.ToList());
            }
            return RedirectPermanent("~/Home/Index");
        }

        // GET: LoaiHangs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiHang loaiHang = db.LoaiHangs.Find(id);
            if (loaiHang == null)
            {
                return HttpNotFound();
            }
            return View(loaiHang);
        }

        // GET: LoaiHangs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: LoaiHangs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "MaLoai,TenLoai")] LoaiHang loaiHang)
        {
            if (ModelState.IsValid)
            {
                db.LoaiHangs.Add(loaiHang);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(loaiHang);
        }

        // GET: LoaiHangs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiHang loaiHang = db.LoaiHangs.Find(id);
            if (loaiHang == null)
            {
                return HttpNotFound();
            }
            return View(loaiHang);
        }

        // POST: LoaiHangs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaLoai,TenLoai")] LoaiHang loaiHang)
        {
            if (ModelState.IsValid)
            {
                db.Entry(loaiHang).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(loaiHang);
        }

        // GET: LoaiHangs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            LoaiHang loaiHang = db.LoaiHangs.Find(id);
            if (loaiHang == null)
            {
                return HttpNotFound();
            }
            return View(loaiHang);
        }

        // POST: LoaiHangs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            LoaiHang loaiHang = db.LoaiHangs.Find(id);
            db.LoaiHangs.Remove(loaiHang);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Controllers/SanPhamsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FashionStore.Models;
using PagedList;
using System.IO;

namespace FashionStore.Areas.Admin.Controllers

{
    public class SanPhamsController : Controller
    {
        private FashionStoreEntities db = new FashionStoreEntities();

        // GET: SanPhams
        public ActionResult Index(string searchString)
        {
            ViewBag.SearchString = searchString;

            var sanPhams = db.SanPhams.Include(s => s.LoaiHang).Include(s => s.NhaCungCap);

            // Filter by product name if searchString is not empty
            if (!string.IsNullOrEmpty(searchString))
            {
                sanPhams = sanPhams.Where(s => s.TenSP.Contains(searchString));
            }

            var u = Session["use"] as FashionStore.Models.TaiKhoan;
            if (u.PhanQuyen.TenQuyen == "Adminstrator")
            {
                return View(sanPhams.OrderByDescending(s => s.MaSP).ToList());
            }

            return RedirectPermanent("~/Home/Index");
        }

        public ActionResult GetProductImage(string imageName)
        {
            if (string.IsNullOrEmpty(imageName))
            {
                return null;
            }

            var imagePath = Server.MapPath("~/Images/" + imageName);
            if (System.IO.File.Exists(imagePath))
            {
                return File(imagePath, "image/jpeg"); // hoặc "image/png" tùy vào định dạng ảnh
            }
            return null;
        }


        // GET: SanPhams/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // GET: SanPhams/Create
        // GET: SanPhams/Create
        public ActionResult Create()
        {
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai");
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC");
            return View();
        }

        // POST: SanPhams/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(SanPham sanPham, HttpPostedFileBase AnhSP)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    if (sanPham.GiaBan.ToString().Contains(","))
                    {
                        string giaBanStr = sanPham.GiaBan.ToString().Replace(",", "");
                        decimal giaBan;
                        if (decimal.TryParse(giaBanStr, out giaBan))
                        {
                            sanPham.GiaBan = giaBan;
                        }
                    }

                    // Kiểm tra nếu người dùng chọn ảnh
                    if (AnhSP != null && AnhSP.ContentLength > 0)
                    {
                        // Tạo tên ảnh mới (chắc chắn không trùng lặp)
                        string fileName = Path.GetFileName(AnhSP.FileName);
                        string filePath = Path.Combine(Server.MapPath("~/Images"), fileName);

                        // Lưu ảnh vào thư mục "Images/Products" trong dự án
                        AnhSP.SaveAs(filePath);

                        // Lưu tên ảnh vào thuộc tính AnhSP của sản phẩm
                        sanPham.AnhSP = fileName;
                    }

                    // Thêm sản phẩm vào database
                    db.SanPhams.Add(sanPham);
                    db.SaveChanges();

                    // Chuyển hướng về trang Index sau khi thêm sản phẩm thành công
                    TempData["SuccessMessage"] = "Thêm sản phẩm thành công!";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex) {
                TempData["ErrorMessage"] = "Có lỗi xảy ra: " + ex.Message;
            }

            // Nếu có lỗi, hiển thị lại form với thông tin đã nhập
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sanPham.MaNCC);
            return View(sanPham);
        }



        // GET: SanPhams/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            ViewBag.MaLoai = new SelectList(db.LoaiHangs, "MaLoai", "TenLoai", sanPham.MaLoai);
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps, "MaNCC", "TenNCC", sanPham.MaNCC);
            return View(sanPham);
        }

        // POST: SanPhams/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "MaSP,TenSP,GiaBan,SoLuong,MoTa,MaLoai,MaNCC,AnhSP")] SanPham sanPham, HttpPostedFileBase imageInput)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (sanPham.GiaBan.ToString().Contains(","))
                    {
                        string giaBanStr = sanPham.GiaBan.ToString().Replace(",", "");
                        decimal giaBan;
                        if (decimal.TryParse(giaBanStr, out giaBan))
                        {
                            sanPham.GiaBan = giaBan;
                        }
                    }

                    // Xử lý upload ảnh nếu có
                    if (imageInput != null && imageInput.ContentLength > 0)
                    {
                        var fileName = Path.GetFileName(imageInput.FileName);
                        var uniqueFileName = Guid.NewGuid().ToString() + "_" + fileName; // Tạo tên file duy nhất
                        var path = Path.Combine(Server.MapPath("~/Images"), uniqueFileName);
                        imageInput.SaveAs(path);
                        sanPham.AnhSP = uniqueFileName; // Cập nhật tên file mới
                    }


                    db.Entry(sanPham).State = EntityState.Modified;
                    db.SaveChanges();

                    return Json(new { success = true });
                }
                return Json(new { success = false, message = "Dữ liệu không hợp lệ" });
            }
            catch (Exception ex)
            {
                return Json(new { success = false, message = "Có lỗi xảy ra: " + ex.Message });
            }
        }


        // GET: SanPhams/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham sanPham = db.SanPhams.Find(id);
            if (sanPham == null)
            {
                return HttpNotFound();
            }
            return View(sanPham);
        }

        // POST: SanPhams/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SanPham sanPham = db.SanPhams.Find(id);
            db.SanPhams.Remove(sanPham);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Areas/Admin/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Trang quản trị";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

<style>
    .admin-dashboard {
        padding: 30px;
    }

    .welcome-section {
        background: linear-gradient(135deg, #2c3e50, #3498db);
        color: white;
        padding: 40px;
        border-radius: 15px;
        margin-bottom: 40px;
        box-shadow: 0 5px 15px rgba(0,0,0,0.1);
    }

    .stats-container {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
        gap: 20px;
        margin-bottom: 40px;
    }

    .stat-card {
        background: white;
        padding: 25px;
        border-radius: 10px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
        transition: transform 0.3s ease;
    }

        .stat-card:hover {
            transform: translateY(-5px);
        }

    .stat-icon {
        font-size: 40px;
        margin-bottom: 15px;
        color: #3498db;
    }

    .stat-number {
        font-size: 28px;
        font-weight: bold;
        color: #2c3e50;
        margin-bottom: 5px;
    }

    .stat-label {
        color: #7f8c8d;
        font-size: 16px;
    }

    .quick-actions {
        background: white;
        padding: 30px;
        border-radius: 15px;
        box-shadow: 0 2px 10px rgba(0,0,0,0.05);
    }

    .action-buttons {
        display: grid;
        grid-template-columns: repeat(auto-fit, minmax(200px, 1fr));
        gap: 15px;
        margin-top: 20px;
    }

    .action-button {
        padding: 15px 25px;
        border: none;
        border-radius: 8px;
        color: white;
        font-weight: 500;
        cursor: pointer;
        transition: all 0.3s ease;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
    }

    .btn-primary {
        background: #3498db;
    }

    .btn-success {
        background: #2ecc71;
    }

    .btn-warning {
        background: #f1c40f;
    }

    .btn-info {
        background: #9b59b6;
    }

    .action-button:hover {
        transform: translateY(-2px);
        box-shadow: 0 5px 15px rgba(0,0,0,0.1);
    }

    .section-title {
        color: #2c3e50;
        margin-bottom: 20px;
        font-weight: 600;
    }
</style>

<div class="admin-dashboard">
    <!-- Welcome Section -->
    <div class="welcome-section">
        <h1>Chào mừng đến với Trang Quản Trị</h1>
        <p>Hệ thống quản lý thời trang nam nữ chuyên nghiệp</p>
    </div>

    <!-- Statistics Section -->
    <div class="stats-container">
        <div class="stat-card">
            <i class="fas fa-shopping-bag stat-icon"></i>
            <div class="stat-number">@ViewBag.TotalOrders</div>
            <div class="stat-label">Đơn hàng</div>
        </div>

        <div class="stat-card">
            <i class="fas fa-users stat-icon"></i>
            <div class="stat-number">@ViewBag.TotalCustomers</div>
            <div class="stat-label">Khách hàng</div>
        </div>

        <div class="stat-card">
            <i class="fas fa-tshirt stat-icon"></i>
            <div class="stat-number">@ViewBag.TotalProducts</div>
            <div class="stat-label">Sản phẩm</div>
        </div>

        <div class="stat-card">
            <i class="fas fa-dollar-sign stat-icon"></i>
            <div class="stat-number">@ViewBag.TotalRevenue</div>
            <div class="stat-label">Doanh thu</div>
        </div>
    </div>

    <!-- Quick Actions Section -->
    <div class="quick-actions">
        <h3 class="section-title">Thao tác nhanh</h3>
        <div class="action-buttons">
            <a href="@Url.Action("Create", "SanPhams")" class="action-button btn-primary">
                <i class="fas fa-plus"></i>
                Thêm sản phẩm mới
            </a>
            <a href="@Url.Action("Index", "DonHangs")" class="action-button btn-success">
                <i class="fas fa-list"></i>
                Quản lý đơn hàng
            </a>
            <a href="@Url.Action("Index", "LoaiHangs")" class="action-button btn-warning">
                <i class="fas fa-tags"></i>
                Quản lý danh mục
            </a>
            <a href="@Url.Action("Index", "TaiKhoans")" class="action-button btn-info">
                <i class="fas fa-user"></i>
                Quản lý người dùng
            </a>
        </div>
    </div>
</div>

<!-- Thêm Font Awesome nếu chưa có trong layout -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">